### ISSUE TITLE
PyPi package missing PyNotion.py

### ISSUE THREAD

**Issue by gene1wood** [bradleyhurley/PyNotion#1]
It appears that the PyPi package, https://pypi.org/project/PyNotion/ wasn't packaged and uploaded correctly as it's missing the main module, `PyNotion.py`

As a result if you do
```
pip install PyNotion
python -c "import PyNotion"
```

You get

```
ModuleNotFoundError: No module named 'PyNotion'
```

**Comment by bradleyhurley** [comment]
@gene1wood - Were you able to move forward by using the syntax in the ReadMe?
```
from PyNotion import PyNotion
```

**Comment by gene1wood** [comment]
@bradleyhurley No, it doesn't work in either case. 

The reason is that if you pull down the actual package hosted with Pypi : https://files.pythonhosted.org/packages/c8/4d/6851ad26254df60b4763038484278f238aa8c1bcbe1b83878b845131ab7b/PyNotion-0.0.1-py3-none-any.whl

and unzip it, you'll find that the `PyNotion.py` module didn't actually make it into the package (it's missing).

Anyhow, not urgent, as I ended up just using your package as a guide and implementing a few `requests` calls on my own. Your code is invaluable though because I, for the life of me, can't find any extant reference to Notion's API anywhere.

docs.getnotion.com is gone. Looking at it on archive.org ( https://web.archive.org/web/20160404000946/http://docs.getnotion.com ) and I can see some reference to the endpoints but the auth mentioned there is all OAuth based (unlike your code).

So your code that talks about provisioning the token is very useful.

**Comment by bradleyhurley** [comment]
Sorry about that - I just pushed a new version
https://pypi.org/project/PyNotion/

**Comment by bradleyhurley** [comment]
I reached out to Notion and they said to their knowledge they never publicly hosted API docs. Truthfully, I don't even have the sensor anymore. A buddy of mine worked for Notion a few years ago and sent me some sensor and this was a fun little project.

**Comment by gene1wood** [comment]
> Sorry about that - I just pushed a new version

Confirmed, that fixed it.

> I reached out to Notion and they said to their knowledge they never publicly hosted API docs.

Interesting. Well however you figured out how to interact with their API and capturing it here, I appreciate it.
